<a href="https://colab.research.google.com/github/ryan121406/ATM/blob/main/P_106.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import plotly.express as px
import pandas as pd
import csv
from numpy import genfromtxt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving data2.csv to data2.csv
Saving data1 (1).csv to data1 (1).csv


In [3]:
df1 = pd.read_csv('data2.csv')
df1

week  Coffee in ml  sleep in hours
0     1            20              89
1     2            30              75
2     3            45              65
3     4            50              40
4     5            60              20
5     6            80              10

In [25]:
def findCorrelation(data1,data2):
  correlation = np.corrcoef(data1,data2)
  print(correlation)

def plot(data1,data2):
  fig = px.scatter(x = data1, y = data2)
  fig.show()

def getData():
  totalData = genfromtxt('data2.csv', delimiter=',')
  print(totalData)
  deleteData = np.delete(totalData,0,0)
  print(deleteData)
  myArrayData1 = deleteData[:,1]
  myArrayData2 = deleteData[:,2]
  return (myArrayData1, myArrayData2)


def main():
  data1, data2 = getData()
  findCorrelation(data1,data2)
  plot(data1,data2)
  
main()

[[nan nan nan]
 [ 1. 20. 89.]
 [ 2. 30. 75.]
 [ 3. 45. 65.]
 [ 4. 50. 40.]
 [ 5. 60. 20.]
 [ 6. 80. 10.]]
[[ 1. 20. 89.]
 [ 2. 30. 75.]
 [ 3. 45. 65.]
 [ 4. 50. 40.]
 [ 5. 60. 20.]
 [ 6. 80. 10.]]
[[ 1.         -0.96306147]
 [-0.96306147  1.        ]]
